/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LiveRouteImport } from './routes/live'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BiographyRouteImport } from './routes/biography'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as StudyOldRouteImport } from './routes/study/old'
import { Route as StudyIdRouteImport } from './routes/study/$id'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BiographyRoute = BiographyRouteImport.update({
  id: '/biography',
  path: '/biography',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyOldRoute = StudyOldRouteImport.update({
  id: '/study/old',
  path: '/study/old',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdRoute = StudyIdRouteImport.update({
  id: '/study/$id',
  path: '/study/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/social': typeof SocialRoute
  '/study/$id': typeof StudyIdRoute
  '/study/old': typeof StudyOldRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/social': typeof SocialRoute
  '/study/$id': typeof StudyIdRoute
  '/study/old': typeof StudyOldRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/social': typeof SocialRoute
  '/study/$id': typeof StudyIdRoute
  '/study/old': typeof StudyOldRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biography'
    | '/books'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/live'
    | '/news'
    | '/social'
    | '/study/$id'
    | '/study/old'
    | '/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biography'
    | '/books'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/live'
    | '/news'
    | '/social'
    | '/study/$id'
    | '/study/old'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/biography'
    | '/books'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/live'
    | '/news'
    | '/social'
    | '/study/$id'
    | '/study/old'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiographyRoute: typeof BiographyRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LiveRoute: typeof LiveRoute
  NewsRoute: typeof NewsRoute
  SocialRoute: typeof SocialRoute
  StudyIdRoute: typeof StudyIdRoute
  StudyOldRoute: typeof StudyOldRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biography': {
      id: '/biography'
      path: '/biography'
      fullPath: '/biography'
      preLoaderRoute: typeof BiographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/old': {
      id: '/study/old'
      path: '/study/old'
      fullPath: '/study/old'
      preLoaderRoute: typeof StudyOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id': {
      id: '/study/$id'
      path: '/study/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof StudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiographyRoute: BiographyRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LiveRoute: LiveRoute,
  NewsRoute: NewsRoute,
  SocialRoute: SocialRoute,
  StudyIdRoute: StudyIdRoute,
  StudyOldRoute: StudyOldRoute,
  StudyIndexRoute: StudyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
